### PR TITLE
Fix for windows compatibility

### PR DESCRIPTION
**Pull request by peter-rs**

### CODE REVIEW

**Comment by jtgrassie** [comment]
No. That fixes nothing. Worse, it breaks non Windows non Linux.

**Comment by peter-rs** [comment]
This is a fix for one of many windows compile time errors as unistd.h is a
posix only header.

**Comment by jtgrassie** [comment]
"errors" or warnings? unistd.h is included in _at least_ cygwin AND mingw. The whole Monero codebase includes it and that compiles fine on Windows – so I'm not going to merge a PR that effectively breaks non-Linux POSIX operating systems.

**Comment by peter-rs** [comment]
Fatal error in my tests with clang and on a separate windows box with msvc.

**Comment by jtgrassie** [comment]
So either install the header in your include path or use MinGW / Cygwin. Not break other operating systems.

**Pull request closed without merging**
