### PR TITLE
claim pypi names, fix setup.py MANIFEST.in

### PR DESCRIPTION
**Pull request by gamesguru**

### CODE REVIEW

**Comment by jtgrassie** [comment]
Please explain why you think this is needed.

**Comment by gamesguru** [comment]
most people prefer to use pypi packages as dependencies

versioned packages can never be changed (and i think removed even?), so it's a more stable environment.  Not that anything would happen to your git repo, but this is the preferred approach

**Comment by jtgrassie** [comment]
1) You are changing the name
 2) It's already versioned. You can just tack on `@commit|tag|branch` to the pip install command.

**Comment by gamesguru** [comment]
It's only versioned by commits?  There are not even tags.  A pypi version is preferred.

Yes the name `pyrx` is already taken by someone on pypi.
Plenty of packages have adapt their name.

**Comment by jtgrassie** [comment]
> It's only versioned by commits? There are not even tags. 

Simply because I haven't bothered adding any tags. The pip commands still honor the version meta-data also (in setup.py).

> A pypi version is preferred.

To you maybe. Not me.

**Comment by jtgrassie** [comment]
Not required and name changed. Closing.

**Pull request closed without merging**
